# This is a basic workflow to help you get started with Actions

name: Build And Deploy Static Site PRODUCTION

# Controls when the workflow will run
on:
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

#
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: runs on branch
      run: echo ${GITHUB_REF##*/}
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
    - name: checkout submodule
      run: |
        git submodule foreach 'git checkout -b  ${GITHUB_REF##*/}'
     # Set the build variables for the job
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: elasticurl
        value: ${{ secrets.ELASTIC_URL_ENDPOINT_PRODUCTION }}
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: elasticsearchurl
        value: ${{ secrets.ELASTIC_SEARCH_URL_PRODUCTION }}
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: elasticcredentials
        value: ${{ secrets.ELASTIC_CREDENTIALS_PRODUCTION }}
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: elasticapikey
        value: ${{ secrets.ELASTIC_API_KEY_PRODUCTION }}
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: elasticindex
        value: ${{ secrets.ELASTIC_INDEX_PRODUCTION }}
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: version
        value: 'main'
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: useindex
        value: 'true'
        
    - uses: actions/setup-node@v2
      with:
        node-version: '17.1.0'
    - run: npm install
    - run: npm run build

    - uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: 'public'
        connection-string: ${{ secrets.AZURE_DOCUMENTATION_STORAGE_CONNECTION_STRING }}

