# This is a basic workflow to help you get started with Actions

name: createPDF

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build_and_create_pdf:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
     # Set the build variables for the job
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: version
        value: 'main'
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: useindex
        value: 'false'
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: productused
        value: 'geomapper'
     # create geomapper pdf   
    - uses: actions/setup-node@v2
      with:
        node-version: '17.1.0'
    - run: npm install
    - run: npm run build-local
    - run: npm run createpdf
     # create geodesigner pdf   
    - uses: jossef/action-set-json-field@v1
      with:
        file: './config/variables/variables.json'
        field: productused
        value: 'geodesigner'
    - run: npm run build-local
    - run: npm run createpdf
    
    # copy all pdf files
    - run: npm run copypdf
    
    - name: Push changes
      run: |
          git config --global user.name 'DorisKoenigshofer'
          git config --global user.email 'doris.koenigshofer@gmail.com'
          git add .
          git commit -m "push actual documentation"
          git push

   
