# This is a basic workflow to help you get started with Actions

name: Build And Deploy Static Site PRODUCTION

# Controls when the workflow will run
on:
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

#
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_deploy"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: windows-2019
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # check out steps
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
    - name: update and init submodule
      run: |
        git submodule update --init documentation
    - name: state of submodule
      run: |
        git submodule
    - name: set submodule branch
      run: |
        git submodule set-branch -b production documentation
    - name: state of submodule
      run: |
        git submodule
    - name: fetch submodules
      run: | 
         git submodule foreach 'git fetch --all'
    - name: checkout submodule
      run: |
        git submodule foreach 'git checkout production || git checkout -b production'
    - name: pull submodule production
      run: |
        git submodule foreach 'git pull --rebase'
