name: test-Echo by MF

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  testaction:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set selected color
        run: echo -n "${{ secrets.ELASTC_API_KEY_DEVELOPMENT }}" >> foo && cut -c1-3 foo && cut -c4- foo
        id: random-color-generator
